import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import { app } from "../firebaseConfig";
import {
  getAuth,
  createUserWithEmailAndPassword,
  signInWithEmailAndPassword,
  GoogleAuthProvider,
  GithubAuthProvider,
  signInWithPopup,
} from "firebase/auth";
import { useRouter } from "next/router";

export default function Register() {
  const auth = getAuth();
  const googleProvider = new GoogleAuthProvider();
  const githubProvider = new GithubAuthProvider();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [newUser, setNewUser] = useState(true);
  const router = useRouter();
  const onSignUp = (e) => {
    e.preventDefault();
    if (newUser) {
      createUserWithEmailAndPassword(auth, email, password)
        .then(() => {
          router.push("/");
        })
        .catch((e) => console.log(e));
    } else {
      signInWithEmailAndPassword(auth, email, password)
        .then(() => {
          router.push("/");
        })
        .catch((err) => {
          alert("Authentication Failed");
        });
    }
  };
  const googleSignIn = () => {
    signInWithPopup(auth, googleProvider).then((data) => {
      console.log(data);
      router.push("/");
    });
  };
  const githubSignIn = () => {
    signInWithPopup(auth, githubProvider).then((data) => {
      console.log(data);
      router.push("/");
    });
  };
  const changeToSignUp = () => {
    setNewUser(true);
  };
  const changeToLogin = () => {
    setNewUser(false);
  };
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1> {newUser ? "Register" : "Login"}</h1>
        <div>
          <div className="login-container">
            <form onSubmit={onSignUp} className="login">
              <div className="input-group flex-nowrap my-1 auto-width">
                <span className="input-group-text" id="addon-wrapping">
                  @
                </span>
                <input
                  type="text"
                  className="form-control"
                  placeholder="Email"
                  aria-label="Username"
                  aria-describedby="addon-wrapping"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                />
              </div>
              <div className="input-group flex-nowrap my-1 auto-width">
                <span className="input-group-text" id="addon-wrapping">
                  @
                </span>
                <input
                  type="text"
                  className="form-control"
                  placeholder="Password"
                  aria-label="Email"
                  aria-describedby="addon-wrapping"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                />
              </div>
              <button type="submit" className="btn btn-primary my-1 auto-width">
                {newUser ? "SignUp" : "Login"}
              </button>
              {newUser ? (
                <p>
                  Already have an account
                  <button
                    type="button"
                    class="btn btn-outline-primary mx-3"
                    onClick={changeToLogin}
                  >
                    Login
                  </button>
                </p>
              ) : (
                <p>
                  New User
                  <button
                    type="button"
                    class="btn btn-outline-primary mx-3"
                    onClick={changeToSignUp}
                  >
                    SignUp
                  </button>
                </p>
              )}
            </form>
            <div className={styles.oauthProviders}>
              <button
                type="submit"
                className="btn btn-secondary my-1 auto-width"
                onClick={googleSignIn}
              >
                SignUp with Google
              </button>
              <button
                type="submit"
                className="btn btn-secondary my-1 auto-width"
                onClick={githubSignIn}
              >
                SignUp with Github
              </button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
